module.exports = {
    "FACTS_EN_US" : {
        "aluminum can":"On average, Americans drink one beverage from an aluminum can every day. But we recycle just over 49 percent of the cans we use. Since the cans are 100 percent recyclable, we could drastically reduce the energy needed to produce brand new cans simply by recycling our empties. Recycling one aluminum can saves enough energy to run a television for three hours.",
		"can":"I am assuming you are talking about aluminum cans. On average, Americans drink one beverage from an aluminum can every day. But we recycle just over 49 percent of the cans we use. Since the cans are 100 percent recyclable, we could drastically reduce the energy needed to produce brand new cans simply by recycling our empties. Recycling one aluminum can saves enough energy to run a television for three hours.",
		"soda can":"On average, Americans drink one beverage from an aluminum can every day. But we recycle just over 49 percent of the cans we use. Since the cans are 100 percent recyclable, we could drastically reduce the energy needed to produce brand new cans simply by recycling our empties. Recycling one aluminum can saves enough energy to run a television for three hours.",
		"aluminum foil":"Aluminum can be recycled almost infinitely. The process involves simply re-melting the metal, a process far less costly and energy-intensive than mining the minerals necessary to create new aluminum. Americans discarded 460,000 tons of foil in 2010. However, Americans are far more likely to recycle aluminum soda cans than aluminum foil.",
		"foil":"Aluminum can be recycled almost infinitely. The process involves simply re-melting the metal, a process far less costly and energy-intensive than mining the minerals necessary to create new aluminum. Americans discarded 460,000 tons of foil in 2010. However, Americans are far more likely to recycle aluminum soda cans than aluminum foil.",
		"steel can": "Steel cans make up about 90 percent of the U.S. food can market. About 71 percent of steel cans are recycled, making them one of the most recycled packaging products in America. Recycling steel saves at least 75 percent of the energy it would take to create steel from raw materials. That\'s enough energy to power 18 million homes.",
		"tin can": "Tin can also called as Steel cans, make up about 90 percent of the U.S. food can market. About 71 percent of steel cans are recycled, making them one of the most recycled packaging products in America. Recycling steel saves at least 75 percent of the energy it would take to create steel from raw materials. That\'s enough energy to power 18 million homes.",
		"soup cans":"Generally known as Steel cans, make up about 90 percent of the U.S. food can market. About 71 percent of steel cans are recycled, making them one of the most recycled packaging products in America. Recycling steel saves at least 75 percent of the energy it would take to create steel from raw materials. That\'s enough energy to power 18 million homes.",
		"veggie cans":"Generally known as Steel cans, make up about 90 percent of the U.S. food can market. About 71 percent of steel cans are recycled, making them one of the most recycled packaging products in America. Recycling steel saves at least 75 percent of the energy it would take to create steel from raw materials. That\'s enough energy to power 18 million homes.",
		"coffee can":"Generally known as Steel cans, make up about 90 percent of the U.S. food can market. About 71 percent of steel cans are recycled, making them one of the most recycled packaging products in America. Recycling steel saves at least 75 percent of the energy it would take to create steel from raw materials. That\'s enough energy to power 18 million homes.",
		"cardboard":"Currently, about 70 percent of cardboard-boxes shipped commercially are recovered for recycling. When recycled, cardboard is used to make chipboard like cereal boxes, paperboard, paper towels, tissues and printing or writing paper. It\'s also made into more corrugated cardboard.",
		"magazine":"Some consumers think glossy paper can\'t be recycled. That may have been true in the early days of recycling, but no longer. About 45 percent of magazines are being recycled today. Recycled magazines are used to make newspaper, tissues, writing paper and paperboard. Recycling just one ton of paper saves enough energy to power the average American home for six months, so don\'t be afraid to recycle your old magazines. It\'s the right thing to do.",
		"office paper":"Just over 45 percent of office paper is recovered for recycling today. If your company generates a large amount of waste paper, consider talking to your local recycling company about whether or not you should sort high-grade papers from lower-grade.",
		"newspaper":"More than 73 percent of all newspapers in the United States are collected and recycled. Recycled newspapers can be made into cereal boxes, egg cartons, pencil barrels, grocery bags, tissue paper and many other products, including new newspapers. Every year natural disasters destroy countless acres of wilderness. The United States Forest Service uses hydro-seeding, to help restore damaged areas. It\'s a planting process that\'s been practiced in the United States since the 1950s - and it all starts with newspapers.",
		"paperboard": "Recycled paperboard is made from 100 percent recovered fiber, which may include newspaper, magazines, corrugated boxboard, paperboard folding cartons, and telephone books. One side of the recycled paperboard is usually gray in color. Be sure the paperboard you have is clean and free of food waste. Then recycle it.",
		"paper":"There are several type of paper. Lets take example of newspaper. More than 73 percent of all newspapers in the United States are collected and recycled. Recycled newspapers can be made into cereal boxes, egg cartons, pencil barrels, grocery bags, tissue paper and many other products, including new newspapers. Every year natural disasters destroy countless acres of wilderness. The United States Forest Service uses hydro-seeding, to help restore damaged areas. It\'s a planting process that\'s been practiced in the United States since the 1950s - and it all starts with newspapers.",
		"plastic":"Plastics come in a variety of shapes, colors and chemical formulations - all with different recycling needs. How can you tell what kinds of plastic to put into your recycling bin? Recycle by shape! Bottles, jars, and jugs – is the best way to know what is accepted."
    }
};